# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='名称')),
                ('original_id', models.CharField(help_text='由15位字符组成', max_length=15, verbose_name='原始ID')),
                ('app_id', models.CharField(help_text='由18位字符组成', max_length=18, verbose_name='应用ID')),
                ('app_secret', models.CharField(help_text='由32位字符组成', max_length=32, verbose_name='应用密钥')),
                ('token', models.CharField(help_text='由32位字符组成', max_length=32, verbose_name='令牌')),
                ('encoding_aes_key', models.CharField(help_text='由43位字符组成', max_length=43, verbose_name='消息加密密钥')),
                ('encrypt_mode', models.CharField(choices=[('safe', '明文模式'), ('compatible', '兼容模式'), ('safe', '安全模式（推荐）')], default='safe', help_text='<p>明文模式下，不使用消息体加解密功能，安全系数较低</p><p>兼容模式下，明文、密文将共存，方便开发者调试和维护</p><p>安全模式下，消息包为纯密文，需要开发者加密和解密，安全系数高</p>', max_length=36, verbose_name='消息加解密方式')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'wechat_detail',
                'verbose_name': '公共号配置',
                'verbose_name_plural': '公共号配置',
            },
        ),
    ]
