# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechatdetail',
            options={'verbose_name': '公共号配置详情', 'verbose_name_plural': '公共号配置详情'},
        ),
        migrations.AddField(
            model_name='wechatdetail',
            name='status',
            field=models.SmallIntegerField(choices=[('safe', '明文模式'), ('compatible', '兼容模式'), ('safe', '安全模式（推荐）')], default=0, verbose_name='状态'),
        ),
    ]
