# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20161118_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatdetail',
            name='encoding_aes_key',
            field=models.CharField(blank=True, default='', help_text='由43位字符组成', max_length=43, verbose_name='消息加密密钥'),
        ),
        migrations.AlterField(
            model_name='wechatdetail',
            name='name',
            field=models.CharField(help_text='[未]', max_length=36, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='wechatdetail',
            name='original_id',
            field=models.CharField(blank=True, default='', help_text='[未]由15位字符组成', max_length=15, verbose_name='原始ID'),
        ),
        migrations.AlterField(
            model_name='wechatdetail',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='[未]备注'),
        ),
    ]
