# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20161122_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatMenuConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=True, verbose_name='是否上线')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='WechatMenuSubConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wm_title', models.CharField(help_text='一级菜单最多4个汉字，二级菜单最多7个汉字，多出来的部分将会以“...”代替。', max_length=36, verbose_name='标题')),
                ('wm_type', models.CharField(choices=[('', '一级菜单（无内容）'), ('click', '点击推事件'), ('view', '跳转URL'), ('scancode_push', '扫码推事件'), ('scancode_waitmsg', '扫码推事件且弹出“消息接收中”提示框'), ('pic_sysphoto', '弹出系统拍照发图'), ('pic_photo_or_album', '弹出拍照或者相册发图'), ('pic_weixin', '弹出微信相册发图器'), ('location_select', '弹出地理位置选择器'), ('media_id', '下发消息（除文本消息）'), ('view_limited', '跳转图文消息URL')], default='', help_text='<a href="http://mp.weixin.qq.com/wiki/home/" target="_blank">详细介绍</a>', max_length=36, verbose_name='菜单类型')),
                ('wm_pos', models.SmallIntegerField(help_text='从上至下 1-7', verbose_name='位置')),
                ('wm_key', models.CharField(blank=True, default='', max_length=255, verbose_name='key | url | media_id')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否可选')),
                ('remark', models.CharField(blank=True, default='', help_text='[未]', max_length=255, verbose_name='备注')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜单子配置',
                'verbose_name_plural': '菜单子配置',
                'db_table': 'wechat_menu',
            },
        ),
        migrations.AlterModelOptions(
            name='wechatdetail',
            options={'verbose_name': '详情配置', 'verbose_name_plural': '详情配置'},
        ),
        migrations.AlterField(
            model_name='wechatdetail',
            name='remark',
            field=models.CharField(blank=True, default='', help_text='[未]', max_length=255, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='wechatmenuconfig',
            name='level_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_menu', to='wechat.WechatMenuSubConfig', verbose_name='一级菜单'),
        ),
        migrations.AddField(
            model_name='wechatmenuconfig',
            name='level_2',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='select_menus', to='wechat.WechatMenuSubConfig', verbose_name='耳机菜单'),
        ),
    ]
