# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_auto_20161125_1410'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wechatmenusubconfig',
            table='wechat_sub_menu',
        ),
    ]
