# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_auto_20161125_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.SmallIntegerField(choices=[(1, '文本消息'), (2, '语音消息'), (3, '图片消息'), (4, '视频消息'), (5, '小视频消息'), (6, '链接消息'), (7, '发送位置消息'), (8, '语音消息'), (9, '事件信息')], default=1, verbose_name='消息类型')),
                ('msg', models.CharField(blank=True, default='', max_length=255, verbose_name='消息内容')),
                ('msg_file', models.FileField(blank=True, default='', upload_to='private/wechat/msg_file/', verbose_name='消息文件')),
                ('is_replied', models.BooleanField(default=False, verbose_name='是否已回复')),
                ('reply_msg', models.CharField(blank=True, default='', max_length=255, verbose_name='回复内容')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('w_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.WechatUser')),
            ],
            options={
                'verbose_name': '微信消息',
                'db_table': 'wechat_message_log',
                'verbose_name_plural': '微信消息',
            },
        ),
    ]
