# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0010_wechatmessagelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatmessagelog',
            name='w_user',
        ),
        migrations.AddField(
            model_name='wechatmessagelog',
            name='wx_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wechat.WechatUser'),
        ),
    ]
