# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0011_auto_20161128_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmessagelog',
            name='msg_type',
            field=models.CharField(choices=[('text', '文本消息'), ('voice', '语音消息'), ('image', '图片消息'), ('video', '视频消息'), ('shortvideo', '小视频消息'), ('link', '链接消息'), ('location', '发送位置消息'), ('other', '其他')], default='text', max_length=36, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='wechatmessagelog',
            name='wx_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wechat.WechatUser', verbose_name='微信用户'),
        ),
    ]
