# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0012_auto_20161128_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmessagelog',
            name='msg',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='wechatmessagelog',
            name='reply_msg',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='回复内容'),
        ),
    ]
