# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0013_auto_20161129_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatAutoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='[未]仅助记', max_length=36, verbose_name='名称')),
                ('code_key', models.CharField(max_length=36, verbose_name='程序关键字')),
                ('keyword', models.CharField(help_text='多个以【|】分割', max_length=255, verbose_name='关键字')),
                ('msg_type', models.CharField(choices=[('text', '文本消息'), ('voice', '语音消息'), ('image', '图片消息'), ('video', '视频消息'), ('shortvideo', '小视频消息'), ('link', '链接消息'), ('location', '发送位置消息'), ('other', '其他')], default='text', max_length=36, verbose_name='消息类型')),
                ('reply_msg', models.TextField(verbose_name='回复内容')),
                ('reply_file', models.FileField(blank=True, default='', upload_to='private/wechat/msg_file/reply/', verbose_name='消息文件')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'wechat_auto_reply',
                'verbose_name': '微信自动回复',
                'verbose_name_plural': '微信自动回复',
            },
        ),
        migrations.AddField(
            model_name='wechatmessagelog',
            name='reply_file',
            field=models.FileField(blank=True, default='', upload_to='private/wechat/msg_file/reply/', verbose_name='消息文件'),
        ),
        migrations.AlterField(
            model_name='wechatmessagelog',
            name='msg',
            field=models.TextField(blank=True, default='', verbose_name='消息数据'),
        ),
        migrations.AlterField(
            model_name='wechatmessagelog',
            name='msg_file',
            field=models.FileField(blank=True, default='', upload_to='private/wechat/msg_file/msg/', verbose_name='消息文件'),
        ),
        migrations.AlterField(
            model_name='wechatmessagelog',
            name='reply_msg',
            field=models.TextField(blank=True, default='', verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='备注名称'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='unionid',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='UnionID'),
        ),
    ]
