# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0016_auto_20161129_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatautoreply',
            name='weight',
            field=models.SmallIntegerField(default=0, help_text='数值越大规则越优先，范围：【0-99】', verbose_name='规则权重'),
        ),
        migrations.AlterField(
            model_name='wechatautoreply',
            name='is_online',
            field=models.BooleanField(choices=[(True, '上线'), (False, '下线')], default=True, verbose_name='是否上线'),
        ),
        migrations.AlterField(
            model_name='wechatautoreply',
            name='keyword',
            field=models.CharField(blank=True, default='', help_text='多个以【|】分割，英文不区分大小写，可空', max_length=255, verbose_name='关键字'),
        ),
    ]
