# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0018_auto_20161130_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('tuling', '图灵机器人')], default='tuling', max_length=36, verbose_name='提供商')),
                ('name', models.CharField(max_length=36, verbose_name='机器人名称')),
                ('status', models.SmallIntegerField(choices=[(-1, '废弃'), (0, '备用'), (1, '启用'), (2, '[暂停]')], default=0, verbose_name='状态')),
                ('priority', models.SmallIntegerField(choices=[(0, '最低'), (1, '低'), (2, '较低'), (3, '中'), (4, '较高'), (5, '高'), (6, '最高')], default=0, verbose_name='优先级')),
                ('call_num', models.PositiveSmallIntegerField(default=5000, verbose_name='调用次数')),
                ('api_key', models.CharField(max_length=36, verbose_name='APIkey')),
                ('is_secret', models.BooleanField(default=False, help_text='暂时不支持', verbose_name='是否加密')),
                ('secret', models.CharField(blank=True, default='', max_length=36, verbose_name='加密secret')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机器人详情',
                'db_table': 'robot_detail',
                'verbose_name_plural': '机器人详情',
            },
        ),
        migrations.AlterModelOptions(
            name='wechatdetail',
            options={'verbose_name': '微信详情配置', 'verbose_name_plural': '微信详情配置'},
        ),
        migrations.AlterModelOptions(
            name='wechatmenuconfig',
            options={'verbose_name': '微信菜单配置', 'verbose_name_plural': '微信菜单配置'},
        ),
        migrations.AlterModelOptions(
            name='wechatmenusubconfig',
            options={'verbose_name': '微信菜单子配置', 'verbose_name_plural': '微信菜单子配置'},
        ),
        migrations.AlterField(
            model_name='wechatautoreply',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, '最低'), (1, '低'), (2, '较低'), (3, '中'), (4, '较高'), (5, '高'), (6, '最高')], default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='wechatdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '废弃'), (0, '备用'), (1, '启用'), (2, '[暂停]')], default=0, verbose_name='状态'),
        ),
    ]
