# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0019_auto_20161130_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '废弃'), (0, '备用'), (1, '启用'), (2, '暂停')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wechatautoreply',
            name='keyword',
            field=models.CharField(blank=True, default='', help_text="<p style='font-weight:bold;'>普通消息：</p><p>&nbsp;&nbsp;多个以【|】分割，英文不区分大小写，可不填</p><p>&nbsp;&nbsp;不填，将匹配任何消息，如无特殊需求请保持此配置【优先级】【最低】，如【消息类型】为【文本消息】此配置将使机器人回复失效</p><p style='font-weight:bold;'>事件消息：</p><p>&nbsp;&nbsp;此处需要对应填写，多个以【|】分割，可不填<p>&nbsp;&nbsp;点击事件：对应的key</p><p>&nbsp;&nbsp;其他事件：请留【空】</p>", max_length=255, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='wechatautoreply',
            name='msg_type',
            field=models.CharField(choices=[('text', '文本消息'), ('voice', '语音消息'), ('image', '图片消息'), ('video', '视频消息'), ('shortvideo', '小视频消息'), ('link', '链接消息'), ('location', '发送位置消息'), (-999, '--以下为事件消息--'), ('click', '点击事件'), ('subscribe#new', '首次关注事件'), ('subscribe#old', '再次关注事件'), ('unsubscribe', '取消关注事件'), ('scan', '已关注扫描事件'), ('location', '地理位置事件'), ('view', '跳转链接事件'), ('templatesendjobfinish', '模板消息事件')], default='text', max_length=36, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='wechatautoreply',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, '最低'), (1, '低'), (2, '较低'), (3, '中'), (4, '较高'), (5, '高'), (6, '最高')], default=0, help_text='所有【事件消息】将忽略优先级配置', verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='wechatautoreply',
            name='reply_msg',
            field=models.TextField(help_text="<p>没有具体要求，可以使用a标签</p><p style='font-weight:bold;'>动态关键词：</p><p>目前支持部分动态关键词，可在对应事件中添加：</p><p>&nbsp;&nbsp;关注事件：昵称{nickname}</p>", verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='wechatdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '废弃'), (0, '备用'), (1, '启用'), (2, '暂停')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wechatmessagelog',
            name='msg_type',
            field=models.CharField(choices=[('text', '文本消息'), ('voice', '语音消息'), ('image', '图片消息'), ('video', '视频消息'), ('shortvideo', '小视频消息'), ('link', '链接消息'), ('location', '发送位置消息')], default='text', max_length=36, verbose_name='消息类型'),
        ),
    ]
