# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0020_auto_20161212_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wechatuser',
            old_name='subscribe',
            new_name='is_subscribe',
        ),
        migrations.AddField(
            model_name='wechatdetail',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
    ]
