# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0021_auto_20161212_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatdetail',
            name='original_id',
            field=models.CharField(help_text='由15位字符组成', max_length=15, unique=True, verbose_name='原始ID'),
        ),
    ]
